config/routes.rb
Rails.application.routes.draw do
  resources :foos
  root 'foos#index'

end

app/models/foo.rb
class Foo < ActiveRecord::Base
  include SpreadsheetArchitect

  def computed_float
    int_number.to_f / 100
  end
  
  #def spreadsheet_columns
  #  [:id, :int_number, :float_number, :decimal_number, :date, :name, :computed_float]
  #end

  #def spreadsheet_columns
  #  [
  #    ['Id', :id, :integer], 
  #    ['Int Number', :int_number, :integer], 
  #    ['Float Number', :float_number, :float],
  #    ['Decimal Number', :decimal_number, :float],
  #    ['Date', :date, :date],
  #    ['Name', :name, :string],
  #    ['Computed Float', :computed_float, :float]
  #  ]
  #end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :xlsx, :ods

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foos_controller.rb
class FoosController < ApplicationController
  before_action :set_foo, only: [:show, :edit, :update, :destroy]

  # GET /foos
  # GET /foos.json
  def index
    @foos = Foo.all
    respond_with @foos
  end

  # GET /foos/1
  # GET /foos/1.json
  def show
  end

  # GET /foos/new
  def new
    @foo = Foo.new
  end

  # GET /foos/1/edit
  def edit
  end

  # POST /foos
  # POST /foos.json
  def create
    @foo = Foo.new(foo_params)

    respond_to do |format|
      if @foo.save
        format.html { redirect_to @foo, notice: 'Foo was successfully created.' }
        format.json { render :show, status: :created, location: @foo }
      else
        format.html { render :new }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foos/1
  # PATCH/PUT /foos/1.json
  def update
    respond_to do |format|
      if @foo.update(foo_params)
        format.html { redirect_to @foo, notice: 'Foo was successfully updated.' }
        format.json { render :show, status: :ok, location: @foo }
      else
        format.html { render :edit }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foos/1
  # DELETE /foos/1.json
  def destroy
    @foo.destroy
    respond_to do |format|
      format.html { redirect_to foos_url, notice: 'Foo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foo
      @foo = Foo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foo_params
      params.require(:foo).permit(:int_number, :float_number, :decimal_number, :date, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foos_helper.rb
module FoosHelper
end

app/views/foos/_form.html.erb
<%= form_for(@foo) do |f| %>
  <% if @foo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
      <% @foo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :int_number %><br>
    <%= f.number_field :int_number %>
  </div>
  <div class="field">
    <%= f.label :float_number %><br>
    <%= f.text_field :float_number %>
  </div>
  <div class="field">
    <%= f.label :decimal_number %><br>
    <%= f.text_field :decimal_number %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foos/edit.html.erb
<h1>Editing Foo</h1>

<%= render 'form' %>

<%= link_to 'Show', @foo %> |
<%= link_to 'Back', foos_path %>

app/views/foos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foos</h1>

<table>
  <thead>
    <tr>
      <th>Int number</th>
      <th>Float number</th>
      <th>Decimal number</th>
      <th>Date</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foos.each do |foo| %>
      <tr>
        <td><%= foo.int_number %></td>
        <td><%= foo.float_number %></td>
        <td><%= foo.decimal_number %></td>
        <td><%= foo.date %></td>
        <td><%= foo.name %></td>
        <td><%= link_to 'Show', foo %></td>
        <td><%= link_to 'Edit', edit_foo_path(foo) %></td>
        <td><%= link_to 'Destroy', foo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foo', new_foo_path %>

app/views/foos/new.html.erb
<h1>New Foo</h1>

<%= render 'form' %>

<%= link_to 'Back', foos_path %>

app/views/foos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Int number:</strong>
  <%= @foo.int_number %>
</p>

<p>
  <strong>Float number:</strong>
  <%= @foo.float_number %>
</p>

<p>
  <strong>Decimal number:</strong>
  <%= @foo.decimal_number %>
</p>

<p>
  <strong>Date:</strong>
  <%= @foo.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @foo.name %>
</p>

<%= link_to 'Edit', edit_foo_path(@foo) %> |
<%= link_to 'Back', foos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpreadsheetTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>